import { Cabin } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";

const fontFamily = Cabin({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontFamily.className}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
